### ISSUE TITLE
Cannot use pgxc_ ctl

### ISSUE THREAD

**Issue by pupillord** [polardb/PolarDB-for-PostgreSQL#14]
I followed the README, but pgxc_ctl binary was not generated.
So I took advice from others, run "make install to generate pgxc_ctl binary file in PGXC_CTL_HOME".

It does generate pgxc_ctl binary. 
But if you use it, you will get an error:
> /usr/bin/bash
> /home/postgres/polardb/polardbhome/bin/pgxc_ctl is not directory.  Check your configurfation

**Comment by yuwei-michael** [comment]
Hi pupillord, Thank you for feecback! The issue what you meet is because "PG_INSTALL" environment variables path not include in "PATH" environment variables.

In build.sh script, it will build all binary include pgxc_ctl. but the default PG_INSTALL path in build.sh is different with what introduce in readme,  it's unified already, please update the code and try again. 

PGXC_CTL_HOME is pgxc_ctl runtime environment, will cache parameter, log etc ,  if don't set will save those file to $HOME/pgxc_ctl.

**Comment by pupillord** [comment]
I got new code and readme，but it still doesn't work.
I wonder if there is any difference between the two environment variables when polardb is started through "./build.sh" and "./onekey.sh" ?

**Comment by yuwei-michael** [comment]
Hi Pupillord, Please set PATH and LD_LIBRARY_PATH to ~/.bashrc, we have colleague find similar issue when set environment variables in ~/.bash_profile, when he set set environment to ~/.bashrc, all work.

**Comment by pupillord** [comment]
The following is my environment variables in ~/.bashrc :
```
export PGUSER=postgres
export PGHOME=/home/postgres/polardb/polardbhome

export LD_LIBRARY_PATH=$PGHOME/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/lib:/usr/lib:/usr/local/lib
export PATH=$PGHOME/bin:$PATH
```
Still reporting errors: 
```
pgxc_ctl: Command not found
```
——————————————————————————————————
when I setup environment variables:
```
export PATH="$HOME/polardb/polarxhome/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/polardb/polarxhome/lib:$LD_LIBRARY_PATH"
```
I could run "./onekey.sh all" , but I need to input the password constantly later, so I stop it.

**Comment by pupillord** [comment]
I changed the environment variables as follows:
```
export PGHOME=$HOME/polardb/polardbhome
```
I can run normally, but I still face a problem, that is I need to input the user password all the time.

**Comment by pupillord** [comment]
![I{L5~8@B~7W7P_7Z2VB1XXS](https://user-images.githubusercontent.com/51103574/120574418-d7fcdc00-c451-11eb-8fe2-6157597a5589.png)

**Comment by yuwei-michael** [comment]
Hi pupillord,

Thank you for upload your issue pictures. We find you try to setup PolarDB by root user,  you can consider to create new separate system user for PolarDB setup. 

For password issue, it's because pgxc_ctl will call some system command like scp to deploy binary etc. those command need input password, if you don't want to input password every time, you can setup mutual trust for you system by ssh-copy-id command, eg "ssh-copy-id username@192.168.2.156".  

if you want to setup Paxos HA in different machine, you can fix IP or other parameter in polardb_paxos.conf after you generate configure by 'pgxc_ctl -c $HOME/polardb/polardb_paxos.conf prepare standalone'. In this scenario, you need setup mutual trust by ssh-copy-id command for each machine, also include current machine. like  ssh-copy-id username@IP1, ssh-copy-id username@IP2, ssh-copy-id username@IP3.

**Comment by pupillord** [comment]
Thanks for help！
Now I can experience the polardb.

**Comment by yuwei-michael** [comment]
@pupillord That's great, enjoy! :)
