### ISSUE TITLE
Official RPM spec file for RHEL and derivates

### ISSUE THREAD

**Issue by einar-hjortdal** [polardb/PolarDB-for-PostgreSQL#219]
PostgreSQL offers an official RPM repository for RHEL (and RHEL-based linux distributions) which includes several versions of PostgreSQL. 

Considering that PolarDB for PostgreSQL is an Alibaba product, and Alibaba Cloud Linux is supposedly compatible with RHEL, I would like to request an officially supported RPMset (which includes .spec file and required patches) **of the stable branch** of this repository for RHEL and derivate distributions.

With such RPMset it would be easy for people running any RHEL-based distribution (including OpenAnolis, upstream of Alibaba Cloud Linux) to package and install PolarDB for PostgreSQL.

**Comment by mrdrivingduck** [comment]
Hi, thanks for your attention to PolarDB for PostgreSQL.

Currently, PolarDB has some special dependencies which is not convenient to packaged as RPM.

However, we are trying to make the deployment of PolarDB as easy as we can. We have already come up with a [development image](https://hub.docker.com/r/polardb/polardb_pg_devel/tags) on DockerHub, which has all you need to build and deploy PolarDB inside a container. Clone the code and build the DB instance are just a matter of several commands.

In the future, we are planning to publish Docker images with instances already built inside, so that users can run the container and use PolarDB directly.

If you have any further questions, free to go on.
