### ISSUE TITLE
Should we force full English communicate for all reply?

### ISSUE THREAD

**Issue by zopyx** [polardb/PolarDB-for-PostgreSQL#22]
If you open-source a project, then ensure that everyone is able to participate. 
English is spoken by everyone in the open-source communities.
Either accept this fact and ensure that every communication is in English AND NOT in Chinese.

如果你開源一個項目，那麼確保每個人都能參與。
開源社區中的每個人都說英語。
要么接受這個事實，並確保每一次交流都是用英語而不是中文，要么把你的項目移到不同的地方。

**Comment by yu199195** [comment]
。。。。。

**Comment by yuwei-michael** [comment]
> If you open-source a project, then ensure that everyone is able to participate.
> English is spoken by everyone in the open-source communities.
> Either accept this fact and ensure that every communication is in English AND NOT in Chinese or move your projects please to a different place.
> 
> 如果你開源一個項目，那麼確保每個人都能參與。
> 開源社區中的每個人都說英語。
> 要么接受這個事實，並確保每一次交流都是用英語而不是中文，要么把你的項目移到不同的地方。

Hi Zopyx, 

Thank you for your suggestion and opinion. I am full agree your opinion about "If you open-source a project, then ensure that everyone is able to participate.", and I am also full understand what your feeling about you meet so many Chinese when you look this webpage. I ever work in Israel and USA for years, I ever hope everyone speak English also. :) Based on our early discuss, and consider your request and feeling, we got some common rules, hope you help check and verify, if you have any doubt, please let me to know , we are open mind community, anything can be discuss with polite attitude.

1. We hope everyone raise opinion and have hotness discuss. but must be polite attitude. otherwise the reply will be delete base on your suggestion. and I had delete some reply since the wording is impolite.

2. In our team, we will use English by default. and base on my experience cooperation with foreign team, if any foreigner on the spot，we will speak English. It's not only for talk but also it's respect!

3. Beside our team, we don't hope to force speak English or Chinese or German etc. and we will try to reply the question by quizzer language, you know the Language is just an instrument for communication, the opinion is more important. For important issue, we will reply by bilingual, and make you understand easily. Based on my experience, if force to use English may get bad communication results. You know the English level is different for everyone, force english will get more misunderstand, and more difficult to know each other sometime.

So We will keep the relevant contents is english and don't have any impolite wording in the discuss group. For other Chinese part, you may ignore, or you can try to translate by google if you want to learn more Chinese, or you want know what the guys talk about. I think we will became good friends when we know each other more. :)

**Comment by byronyi** [comment]
@zopyx You are posting discriminatory content. I am reporting this to GitHub.

**Comment by zopyx** [comment]
> @zopyx You are posting discriminatory content. I am reporting this to GitHub.

Do it. But perhaps you should learn how to handle open-source projects before releasing something.

**Comment by byronyi** [comment]
> Chinese or move your projects please to a different place.
> This is very arrogant to communicate in Chinese hereChinese.

You are in no position to accuse someone else being arrogant, unless they pose exactly the same accusation to you first.

And it is YOU being arrogant here, so please just go away.

**Comment by yuwei-michael** [comment]
Hi Guys, We got some misunderstanding at beginning,  now we have got common rules based on all our opinion, please check and confirm, if any doubt, we can fix it as soon as possible, then we can stop useless squabble.

**Comment by zopyx** [comment]
> > Chinese or move your projects please to a different place.
> > This is very arrogant to communicate in Chinese hereChinese.
> 
> You are in no position to accuse someone else being arrogant, unless they pose exactly the same accusation to you first.
> 
> And it is YOU being arrogant here, so please just go away.

Will do..obviously you do not care about community building and about contributions and feedback from outside the Chinese world...your problem...good luck :)

**Comment by byronyi** [comment]
Of course the maintainers care about community building, only that comes from contributors that submit bug reports and PRs, but not trolls. 

You have deleted your comments, so obviously you KNEW that you are not being well-behaved.

**Comment by stdrc** [comment]
人家种族歧视，你们搁这用英文回复，不是正中下怀？

还故意用繁体中文，不就是来恶心人的吗。

**Comment by richardchien** [comment]
@zopyx 就你这点破开源参与度，有资格代表 GitHub 在这说话么，滑稽，还没一个中国本科生参与开源贡献多

**Comment by XiaoMiku01** [comment]
@zopyx 你寄吧谁啊？

**Comment by zopyx** [comment]
Again, you are unwilling to communicate properly? Do want you want. This project is obviously of zero interest for the English-speaking world (means the rest of the world outside China) 🤷🏻‍♂️

**Comment by byronyi** [comment]
Please don't use hate speech against discriminative content. I am reporting all of them to GitHub.

**Comment by yuwei-michael** [comment]
> Again, you are unwilling to communicate properly? Do want you want. This project is obviously of zero interest for the English-speaking world (means the rest of the world outside China) 🤷🏻‍♂️

Hi Zopyx, I am very respect your opinions and suggestions, and have lots discuss in group for common rules to make all of us to happy, and I have waste more than 1h to reply your part, I hope you like our idea or give more useful suggestion. Do you ever read my reply?  I will post it again.


Hi Zopyx,

Thank you for your suggestion and opinion. I am full agree your opinion about "If you open-source a project, then ensure that everyone is able to participate.", and I am also full understand what your feeling about you meet so many Chinese when you look this webpage. I ever work in Israel and USA for years, I ever hope everyone speak English also. :) Based on our early discuss, and consider your request and feeling, we got some common rules, hope you help check and verify, if you have any doubt, please let me to know , we are open mind community, anything can be discuss with polite attitude.

We hope everyone raise opinion and have hotness discuss. but must be polite attitude. otherwise the reply will be delete base on your suggestion. and I had delete some reply since the wording is impolite.

In our team, we will use English by default. and base on my experience cooperation with foreign team, if any foreigner on the spot，we will speak English. It's not only for talk but also it's respect!

Beside our team, we don't hope to force speak English or Chinese or German etc. and we will try to reply the question by quizzer language, you know the Language is just an instrument for communication, the opinion is more important. For important issue, we will reply by bilingual, and make you understand easily. Based on my experience, if force to use English may get bad communication results. You know the English level is different for everyone, force english will get more misunderstand, and more difficult to know each other sometime.

So We will keep the relevant contents is english and don't have any impolite wording in the discuss group. For other Chinese part, you may ignore, or you can try to translate by google if you want to learn more Chinese, or you want know what the guys talk about. I think we will became good friends when we know each other more. :)

**Comment by yuwei-michael** [comment]
> Again, you are unwilling to communicate properly? Do want you want. This project is obviously of zero interest for the English-speaking world (means the rest of the world outside China) 🤷🏻‍♂️

Hi Zopyx, It's sleeping time in China now, I think no more reply today, hope you can check the reply and make sure what have happened if you have time. if you can read the rules and give more constructive suggestion, it will very helpful to us.😀

**Comment by xuhuleon** [comment]
> If you open-source a project, then ensure that everyone is able to participate.
> English is spoken by everyone in the open-source communities.
> Either accept this fact and ensure that every communication is in English AND NOT in Chinese.
> 
> 如果你開源一個項目，那麼確保每個人都能參與。
> 開源社區中的每個人都說英語。
> 要么接受這個事實，並確保每一次交流都是用英語而不是中文，要么把你的項目移到不同的地方。


It's better to use English in the open source communities.  But could you use Simple Chinese instead of Traditional Chinese? We are modern people now, not in Qing dynasty anymore.

**Comment by yuwei-michael** [comment]
> > If you open-source a project, then ensure that everyone is able to participate.
> > English is spoken by everyone in the open-source communities.
> > Either accept this fact and ensure that every communication is in English AND NOT in Chinese.
> > 如果你開源一個項目，那麼確保每個人都能參與。
> > 開源社區中的每個人都說英語。
> > 要么接受這個事實，並確保每一次交流都是用英語而不是中文，要么把你的項目移到不同的地方。
> 
> It's better to use English in the open source communities. But could you use Simple Chinese instead of Traditional Chinese? We are modern people now, not in Qing dynasty anymore.

I think he don't know what's different about "Simple Chinese" and "Traditional Chinese". and both of them is belong our Chinese nation.

**Comment by KafuuNeko** [comment]
种族歧视者，你没有资格教我们做事，我们有使用中文的权力！

**Comment by stdrc** [comment]
好，原来说事实也能被删

![image](https://user-images.githubusercontent.com/5317095/120669459-0f0ad600-c4c2-11eb-9be2-6c0c87cbdeb8.png)

原来一个外国的地图炮喷子的 issue 不用被删，一个用事实反怼回去的 comment 要被删掉，我笑了

**Comment by yuwei-michael** [comment]
> 好，原来说事实也能被删
> 
> ![image](https://user-images.githubusercontent.com/5317095/120669459-0f0ad600-c4c2-11eb-9be2-6c0c87cbdeb8.png)
> 
> 原来一个外国的地图炮喷子的 issue 不用被删，一个用事实上反怼回去的 comment 要被删掉，我笑了

Hi Richardchien， 你的回复包含人身攻击的内容了，换位思考下，有人这样说我，我肯定不开心啦。zopyx的帖子，最初不好的内容，他自己已经删除了，中文的部分还保留了“在這裡用中文交流是很囂張的。”内容，他知道的话，应该也会删除的。关于用中文还是英文，我觉得是个好问题，群里有那么多外国人，如何才能让大家能更好的交流，确实是值得讨论的，只是开始有人说了脏活，才闹得大家都不愉快的，后面有了规则，这种情况会直接删除评论，这种问题应该就不会发生了。

**Comment by horizonzy** [comment]
### 中文:
如果有人喜欢用中文，用google翻译翻译一下，把对应的英文一起贴下面就行了。不过还是鼓励用英文，毕竟现在全世界的通用语言还是是英文。

> 要么接受這個事實，並確保每一次交流都是用英語而不是中文，要么把你的項目移到不同的地方

@zopyx 为什么不用英文就得把项目移到不同的地方，你也太偏激了，只是鼓励，不是强制，如果你真的需要了解什么信息而没有英文的话，翻译软件也能帮你。

------------------------------------------------------------------------------------------------------------------



### English:
If someone likes to use Chinese, use Google Translate to translate it and paste the corresponding English together below. However, the use of English is still encouraged, after all, the common language in the world is still English.


>要么接受這個事實，並確保每一次交流都是用英語而不是中文，要么把你的項目移到不同的地方

@zopyx Why do you have to move the project to a different place without using English? You are too extreme. It's just encouragement, not mandatory. If you really need to know something and don't have English, translation software can help you.
