### ISSUE TITLE
是否有计划支持windows版本？[Question]

### ISSUE THREAD

**Issue by manfuldrifter** [polardb/PolarDB-for-PostgreSQL#237]
**Describe the problem**

...
类似于postgres的windows版本

**Comment by mrdrivingduck** [comment]
Hi~感谢您对 PolarDB 的关注！

我们没有提供在 Windows 上裸装 PolarDB 的方法，因为解决编译和运行时依赖是一个比较棘手的问题。目前我们主要提倡 [使用 Docker 来进行部署或开发](https://apsaradb.github.io/PolarDB-for-PostgreSQL/zh/deploying/db-localfs.html)，也是想把对环境的配置降低至最少。我们提供的 Docker 开发镜像可以在 Windows 下运行，需要您在 Windows 上安装 [Docker Desktop](https://www.docker.com/get-started/) 并启用相应虚拟化即可（WSL2 / Hyper-V）。经过我们的测试是可以正常编译部署的。

如果您在 Windows 上解决了编译问题并成功编译部署了 PolarDB，并且步骤具有足够的通用性，我们也非常欢迎您向我们的在线文档 [贡献](https://apsaradb.github.io/PolarDB-for-PostgreSQL/zh/contributing/contributing-polardb-docs.html) 您的努力成果 😁

---

Hi~Thanks for your interest to PolarDB!

We haven't provide any way to build or deploy PolarDB **directly** on Windows because solving compilation and runtime dependencies is a tricky problem. At present, we mainly advocate [using Docker for deployment or development](https://apsaradb.github.io/PolarDB-for-PostgreSQL/deploying/db-localfs.html), because we want to minimize the configuration of the environment. The Docker development image we provide can run under Windows, which requires you to install [Docker Desktop](https://www.docker.com/get-started/) on Windows  and enable virtualization (WSL2 / Hyper-V). According to our testing, it can be compiled and deployed normally.

If you have solved compilation problem on Windows and successfully compiled and deployed PolarDB, and the steps are sufficiently generic, we welcome you to contribute the results of your efforts to our [online documentation](https://apsaradb.github.io/PolarDB-for-PostgreSQL/contributing/contributing-polardb-docs.html) 😁
